# Generated by Django 3.0.5 on 2020-04-30 02:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addendum', '0002_auto_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='snippettranslation',
            name='language',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='snippettranslation',
            name='snippet',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='addendum.Snippet'),
        ),
        migrations.AlterField(
            model_name='snippettranslation',
            name='text',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
